from pathlib import Path
import re

activity = Path('app/src/main/java/com/cefalo/angulos/AnalysisActivity.java')
a = activity.read_text(encoding='utf-8')

# Fix the vertical navigation bar. VerticalPanSeekBar updates progress from its
# own touch handler, so Android reports those progress changes as fromUser=false.
# The previous listener discarded them, which made the bar look interactive but
# never move the radiograph. Keep the synchronization guard, but accept the
# progress change generated by the vertical bar itself.
vertical_start = a.find('verticalPanBar.setOnSeekBarChangeListener')
vertical_end = a.find('measurementView.setViewportListener', vertical_start)
if vertical_start < 0 or vertical_end < 0:
    raise RuntimeError('Could not locate vertical pan listener')
vertical_block = a[vertical_start:vertical_end]
old_guard = 'if (!fromUser || syncingViewportBars[0]) return;'
new_guard = 'if (syncingViewportBars[0]) return;'
if old_guard in vertical_block:
    vertical_block = vertical_block.replace(old_guard, new_guard, 1)
elif new_guard not in vertical_block:
    raise RuntimeError('Unexpected vertical pan listener guard')
a = a[:vertical_start] + vertical_block + a[vertical_end:]

# Make the visible landmark buttons substantially smaller. The point itself is
# still selected by tapping the chip, while the radiographic landmark hit area
# remains unchanged in MeasurementView.
a = a.replace('chip.setTextSize(10.5f);', 'chip.setTextSize(9f);')
a = a.replace('chip.setMinWidth(dp(48));', 'chip.setMinWidth(dp(34));')
a = a.replace(
    '''            chip.setPadding(\n                    dp(8),\n                    dp(4),\n                    dp(8),\n                    dp(4)\n            );''',
    '''            chip.setPadding(\n                    dp(5),\n                    dp(2),\n                    dp(5),\n                    dp(2)\n            );'''
)
a = a.replace(
    '''                    new ViewGroup.MarginLayoutParams(\n                            ViewGroup.LayoutParams.WRAP_CONTENT,\n                            dp(48)\n                    );''',
    '''                    new ViewGroup.MarginLayoutParams(\n                            ViewGroup.LayoutParams.WRAP_CONTENT,\n                            dp(34)\n                    );'''
)
a = a.replace('lp.setMargins(dp(2), 0, dp(2), 0);',
              'lp.setMargins(dp(1), 0, dp(1), 0);')
activity.write_text(a, encoding='utf-8')

# Compact the complete landmark strip in portrait, landscape and tablet. This
# frees vertical space and prevents the landmark row from crowding the bottom
# radiograph navigation bar on small phones.
def compact_strip(path: Path):
    if not path.exists():
        return
    s = path.read_text(encoding='utf-8')

    s = re.sub(
        r'(android:id="@\+id/pointStrip"[\s\S]{0,180}?android:layout_height=")64dp(")',
        r'\g<1>44dp\2',
        s,
        count=1,
    )

    # Restrict the next replacements to the pointStrip block only.
    start = s.find('android:id="@+id/pointStrip"')
    if start >= 0:
        end = s.find('</LinearLayout>', start)
        if end >= 0:
            end += len('</LinearLayout>')
            block = s[start:end]
            block = block.replace('android:layout_height="14dp"', 'android:layout_height="10dp"', 1)
            block = block.replace('android:layout_height="12dp"', 'android:layout_height="10dp"', 1)
            block = block.replace('android:layout_height="48dp"', 'android:layout_height="32dp"', 2)
            block = block.replace('android:textSize="9sp"', 'android:textSize="8sp"', 1)
            block = block.replace('android:textSize="8.5sp"', 'android:textSize="8sp"', 1)
            s = s[:start] + block + s[end:]

    path.write_text(s, encoding='utf-8')

for rel in [
    'app/src/main/res/layout/activity_analysis.xml',
    'app/src/main/res/layout-land/activity_analysis.xml',
    'app/src/main/res/layout-sw600dp/activity_analysis.xml',
]:
    compact_strip(Path(rel))

# Bump this UI correction so it is easy to distinguish from the 1.27 package.
gradle = Path('app/build.gradle')
g = gradle.read_text(encoding='utf-8')
g = re.sub(r'versionCode\s+28\b', 'versionCode 29', g, count=1)
g = re.sub(r"versionName\s+'1\.27'", "versionName '1.28'", g, count=1)
gradle.write_text(g, encoding='utf-8')

# Fail the build immediately if the two requested corrections were not applied.
check = activity.read_text(encoding='utf-8')
check_start = check.find('verticalPanBar.setOnSeekBarChangeListener')
check_end = check.find('measurementView.setViewportListener', check_start)
check_block = check[check_start:check_end]
if 'if (syncingViewportBars[0]) return;' not in check_block:
    raise RuntimeError('Vertical pan correction was not applied')
if 'chip.setMinWidth(dp(34));' not in check or 'dp(34)' not in check:
    raise RuntimeError('Compact point chips were not applied')

print('Vertical radiograph navigation fixed and landmark buttons compacted.')
